name: Deploy app to github pages

on:
  push:
    branches: main

jobs:
  deploy-to-run-github-pages:
    runs-on: ubuntu-latest
    steps:
    
    # Clone repository on VM
    - uses: actions/checkout@v3
    
    # Install .NET SDK
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        
    # Generate static files
    - name: Publish project
      run: dotnet publish AquaHelps.Client -c Release --output release --nologo
      
    # Change '/' to '/AquaHelps/'
    - name: Change base-tag in index.html from / to AquaHelps
      run: sed -i 's/<base href="\/" \/>/<base href="\/AquaHelps\/" \/>/g' /release/wwwroot/index.html
    
    # Disable jekyll
    - name: Add .nojekyll file
      run: touch /release/wwwroot/.nojekyll
      
    - name: Uploading files to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: release/wwwroot
